---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  vars:
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: 'connect & retrieve env variables'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - 'env'

  roles:
    - GITHUB.UPDATE.ROLE
    - GITHUB.LINTING.ROLE

  tasks:
    - import_tasks: tasks/1_zsh.yml
    - import_tasks: tasks/2_terminator.yml
