---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  pre_tasks:
    - name: 'Connect to host & retrieve min facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'

  roles:
    - GITHUB.UPDATE.ROLE

  tasks:
    - import_tasks: tasks/1_zsh.yml
    - import_tasks: tasks/2_terminator.yml
